name: CI
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  ci:
    strategy:
      matrix:
        os:
        - windows-latest
        - macos-latest
        - ubuntu-latest
        channel:
        - stable
        - beta
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2

    - uses: UziTech/action-setup-atom@v2
      with:
        version: ${{ matrix.channel }}

    - name: Install dependencies
      run: apm ci

    - name: Run tests
      run: atom --test spec
