name: Publish new version
on:
  workflow_dispatch:
    inputs:
      version:
        description: Version to release
        required: true
        default: patch

jobs:
  publish:
    runs-on: windows-latest
    steps:
    - name: Disable CRLF conversion
      run: git config --global core.autocrlf false

    - uses: actions/checkout@v2

    - uses: UziTech/action-setup-atom@v2

    - name: Install dependencies
      run: apm ci

    - name: Set git identity
      run: |
        $user = Invoke-RestMethod -Method Get -Uri https://api.github.com/users/${{ github.actor }}
        git config user.name $user.name
        git config user.email ($user.email ?? "$($user.id)+${{ github.actor }}@noreply.users.github.com")

    - name: Publish new version
      run: apm publish ${{ github.event.inputs.version }}
      env:
        ATOM_ACCESS_TOKEN: ${{ secrets.ATOM_ACCESS_TOKEN }}
